[n2o5, no2, n2, o2, dt] = calc_concentrations1(1.40,5.2*10^(-3),3.4*10^(-5),0.5);
x = linspace(0,10000,10000/dt);
y = n2o5;
figure(1);
plot (x, y);
hold on;
y = no2;
plot (x, y);
hold on;
y = n2;
plot(x, y);
hold on;
y = o2;
plot(x, y);
legend('N2O5', 'NO2', 'N2', 'O2');
xlabel('time [sec]');
ylabel('concentration [M]');
title('Concentration of N2O5, NO2, N2, O2 Over Time');
d = load('input_data.mat', '-mat');
cell = struct2cell(d);
data_mat = cell2mat(cell);
[A, B] = calc_concentrations2(data_mat, 0.250);
x = data_mat(:, 1);
y = data_mat(:, 2);
figure(2);
plot(x, y);
hold on;
y = A;
plot(x, y);
hold on;
y = B;
plot(x, y);
legend('C', 'A', 'B');
xlabel('time [h]');
ylabel('concentration [M]');
title('Concentration of A, B, C Over Time');
reaction_order(A, x);